id: P003220
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:20.682648
source_metadata:
  id: bdr:W3CN7913
  title: གསུང་འབུམ། ཁྲི་གུང་ཐང་སྐུ་ཕྲེང་དྲུག་པ།
  author: ''
  volumes:
    80facef69b8549abbd76bd4569574c08:
      image_group_id: I3CN7915
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
    939fd0c204624c1193909fa04af6c3dd:
      image_group_id: I3CN7916
      title: ''
      volume_number: 2
      total_pages: 310
      base_file: v002.txt
    e033e9a26b0a4f689ec79b592ee8a7ba:
      image_group_id: I3CN7917
      title: ''
      volume_number: 3
      total_pages: 442
      base_file: v003.txt
    57eb62a74a614c90b7bb4b487e3c3e7c:
      image_group_id: I3CN7918
      title: ''
      volume_number: 4
      total_pages: 358
      base_file: v004.txt
    c8c25f9c06214404a8234c820b54ac19:
      image_group_id: I3CN7919
      title: ''
      volume_number: 5
      total_pages: 194
      base_file: v005.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
