id: I46A944FD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:50:58+00:00'
last_modified: '2022-06-07T18:28:25.366134+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7913
  title: གསུང་འབུམ། ཁྲི་གུང་ཐང་སྐུ་ཕྲེང་དྲུག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '7744':
      image_group_id: I3CN7915
      title: ''
      total_pages: 374
      order: 1
      base_file: 7744.txt
    0E84:
      image_group_id: I3CN7916
      title: ''
      total_pages: 310
      order: 2
      base_file: 0E84.txt
    F334:
      image_group_id: I3CN7917
      title: ''
      total_pages: 442
      order: 3
      base_file: F334.txt
    4AF0:
      image_group_id: I3CN7918
      title: ''
      total_pages: 358
      order: 4
      base_file: 4AF0.txt
    B58B:
      image_group_id: I3CN7919
      title: ''
      total_pages: 194
      order: 5
      base_file: B58B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
